/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDisps {
        "disps": any[] | null;
    }
    interface AppFaves {
    }
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface CheckinCamera {
    }
    interface DispDetail {
        "name": string;
    }
    interface NearMe {
    }
    interface PostDetail {
        "localID": string;
        "postID": string;
    }
}
declare global {
    interface HTMLAppDispsElement extends Components.AppDisps, HTMLStencilElement {
    }
    var HTMLAppDispsElement: {
        prototype: HTMLAppDispsElement;
        new (): HTMLAppDispsElement;
    };
    interface HTMLAppFavesElement extends Components.AppFaves, HTMLStencilElement {
    }
    var HTMLAppFavesElement: {
        prototype: HTMLAppFavesElement;
        new (): HTMLAppFavesElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSettingsElement extends Components.AppSettings, HTMLStencilElement {
    }
    var HTMLAppSettingsElement: {
        prototype: HTMLAppSettingsElement;
        new (): HTMLAppSettingsElement;
    };
    interface HTMLCheckinCameraElement extends Components.CheckinCamera, HTMLStencilElement {
    }
    var HTMLCheckinCameraElement: {
        prototype: HTMLCheckinCameraElement;
        new (): HTMLCheckinCameraElement;
    };
    interface HTMLDispDetailElement extends Components.DispDetail, HTMLStencilElement {
    }
    var HTMLDispDetailElement: {
        prototype: HTMLDispDetailElement;
        new (): HTMLDispDetailElement;
    };
    interface HTMLNearMeElement extends Components.NearMe, HTMLStencilElement {
    }
    var HTMLNearMeElement: {
        prototype: HTMLNearMeElement;
        new (): HTMLNearMeElement;
    };
    interface HTMLPostDetailElement extends Components.PostDetail, HTMLStencilElement {
    }
    var HTMLPostDetailElement: {
        prototype: HTMLPostDetailElement;
        new (): HTMLPostDetailElement;
    };
    interface HTMLElementTagNameMap {
        "app-disps": HTMLAppDispsElement;
        "app-faves": HTMLAppFavesElement;
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-settings": HTMLAppSettingsElement;
        "checkin-camera": HTMLCheckinCameraElement;
        "disp-detail": HTMLDispDetailElement;
        "near-me": HTMLNearMeElement;
        "post-detail": HTMLPostDetailElement;
    }
}
declare namespace LocalJSX {
    interface AppDisps {
        "disps"?: any[] | null;
    }
    interface AppFaves {
    }
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppSettings {
    }
    interface CheckinCamera {
    }
    interface DispDetail {
        "name"?: string;
    }
    interface NearMe {
    }
    interface PostDetail {
        "localID"?: string;
        "postID"?: string;
    }
    interface IntrinsicElements {
        "app-disps": AppDisps;
        "app-faves": AppFaves;
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-settings": AppSettings;
        "checkin-camera": CheckinCamera;
        "disp-detail": DispDetail;
        "near-me": NearMe;
        "post-detail": PostDetail;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-disps": LocalJSX.AppDisps & JSXBase.HTMLAttributes<HTMLAppDispsElement>;
            "app-faves": LocalJSX.AppFaves & JSXBase.HTMLAttributes<HTMLAppFavesElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-settings": LocalJSX.AppSettings & JSXBase.HTMLAttributes<HTMLAppSettingsElement>;
            "checkin-camera": LocalJSX.CheckinCamera & JSXBase.HTMLAttributes<HTMLCheckinCameraElement>;
            "disp-detail": LocalJSX.DispDetail & JSXBase.HTMLAttributes<HTMLDispDetailElement>;
            "near-me": LocalJSX.NearMe & JSXBase.HTMLAttributes<HTMLNearMeElement>;
            "post-detail": LocalJSX.PostDetail & JSXBase.HTMLAttributes<HTMLPostDetailElement>;
        }
    }
}
